name: esp_prov_workspace
publish_to: none

environment:
  sdk: ^3.13.0

workspace:
  - packages/esp_prov_core
  - packages/esp_prov_ble_universal
  - packages/esp_prov
  - packages/esp_prov/example

dev_dependencies:
  very_good_analysis: ^11.0.0
